version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sissep_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER:     sissep_user
      POSTGRES_PASSWORD: sissep_pass
      POSTGRES_DB:       sissep_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U sissep_user -d sissep_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: sissep_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD","mongosh","--eval","db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  mongodata:
